services:
  server:
    build: ./server
    container_name: collatz-server          
    ports:
      - "9000:9000"
    networks:
      - collatz-net

  client:
    build: ./client
    environment:
      - COLLATZ_COUNT=500000
      - SERVER_HOST=collatz-server         
      - SERVER_PORT=9000
    depends_on:
      - server
    networks:
      - collatz-net

networks:
  collatz-net: